"use client";
import "./globals.css";
// import type { Metadata } from "next";

import Link from "next/link";
// import { Geist, Geist_Mono } from "next/font/google";

import { usePathname } from "next/navigation";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  return (
    <html lang="ru">
      <body>
        <div className="flex flex-row justify-between sticky top-0 text-white items-center gap-10 p-5 h-15 bg-black">
          <Link
            className="bg-yellow-300 text-black font-bold text-lg rounded-lg px-4 py-2 flex items-center shadow-md transition duration-200 hover:bg-yellow-400"
            href="/menu">
            T-Перекус
          </Link>
          <div className="flex items-center gap-8">
            <Link
              className={
                pathname.startsWith("/menu")
                  ? "text-yellow-300"
                  : "text-white" +
                    "text-base hover:text-yellow-300 transition duration-200"
              }
              href="/menu">
              Меню
            </Link>
            <Link
              className={
                pathname.startsWith("/shopping_list")
                  ? "text-yellow-300"
                  : "text-white" +
                    "text-base hover:text-yellow-300 transition duration-200"
              }
              href="/shopping_list">
              Что у меня есть
            </Link>
            <Link
              className={
                pathname.startsWith("/recipes")
                  ? "text-yellow-300"
                  : "text-white" +
                    "text-base hover:text-yellow-300 transition duration-200"
              }
              href="/recipes">
              Блюда
            </Link>
            <Link
              className={
                pathname.startsWith("/products")
                  ? "text-yellow-300"
                  : "text-white" +
                    "text-base hover:text-yellow-300 transition duration-200"
              }
              href="/products">
              Продукты
            </Link>
          </div>
        </div>
        <main className="pt-14 p-2 sm:p-4 lg:p-6">{children}</main>
      </body>
    </html>
  );
}
