import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <div className="flex flex-row text-white items-center gap-10 p-5 h-15 bg-black">
          <Link
            className="bg-yellow-300 text-black font-bold text-lg rounded-lg px-4 py-2 flex items-center shadow-md transition duration-200 hover:bg-yellow-400"
            href="/menu">
            T-перекус
          </Link>
          <div className="flex items-center gap-8">
            <Link
              className="text-white text-base hover:text-yellow-300 transition duration-200"
              href="/menu">
              Меню
            </Link>
            <Link
              className="text-white text-base hover:text-yellow-300 transition duration-200"
              href="/shopping_list">
              Список продуктов
            </Link>
            <Link
              className="text-white text-base hover:text-yellow-300 transition duration-200"
              href="/recipes">
              Блюда
            </Link>
          </div>
        </div>
        <main className="pt-14 p-2 sm:p-4 lg:p-6">{children}</main>
      </body>
    </html>
  );
}
