import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        
        <div title="Админ-панель">
          <button className="px-3 py-1 m-5 text-sm bg-gray-500 text-white rounded hover:bg-blue-600 transition">

            Сохранить
          </button>
          <a href="/settings" className="text-gray-600 hover:text-gray-800">
            Настройки
          </a>
        </div>

        {/* 2. Основной контент */}
        <main className="pt-14 p-4 sm:p-6 lg:p-8">
          {/* Важно: Добавьте padding-top (pt-14) к основному контенту, 
             чтобы он не скрывался за фиксированным тулбаром. */}
          {children}
        </main>
      </body>
    </html>
  );
}
